config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  get 'favourites/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'
  get 'users/create'
  get '/about',to: 'home#about'
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :books
  get '/login',to: "sessions#index"
  post '/login',to: "sessions#create"
  delete '/logout',to: "sessions#destroy"
  post '/accept',to: "books#change_status"
  get '/books/get_type', to: "books#get_type"
  get '/search_admin', to: "books#search_admin"
  get '/register',to: "users#new"
  get '/search', to: "books#search_user"

  get '/add_favourite', to: "favourites#change_favourite"
  resources :users
  resources :favourites
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/shared/header/_logo-area.html.erb
 <div class="logo-area text-center">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <!-- Nav brand -->
                        <a href="index.html" class="nav-brand">
                        <%= image_tag ("logo.png")%></a>
                    </div>
                </div>
            </div>
        </div>

app/views/shared/header/_navbar-area.html.erb
<div class="foode-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar" id="foodeNav">

                        <!-- Nav brand -->
                        <a href="index.html" class="nav-brand"><%= image_tag( "logo.png") %></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li>
                                    <%= link_to  "Home",  root_path %>
                                    </li>
                                    <li><a href="#">Categories</a>
                                        <ul class="dropdown">
                                            <%if get_categories.any? %> 
                                                <% get_categories.each do |item| %> 
                                            <li>
                                                <%= link_to  item.category_name, categories_show_path(id: item.id) %>                                              
                                            </li>
                                            <% end %> 
                                            <% end %> 
                                        </ul>
                                    </li>
                                    
                                    
                                    <li>
                                    <%= link_to  "About Us",about_path  %>
                                   
                                    <% if current_user  %> 
                                        <li><a href="contact.html"><%= current_user.user_name  %>  </a>
                                            <ul class="dropdown">
                                               
                                                    <li><%= link_to  "Manage Book", books_path %></li>
                                                   <li><%= link_to  "Favourite Books", favourites_path %></li>
                                                    <li><%= link_to  "Change profile", edit_user_path(current_user)%></li>
                                                    <li><%= link_to  "Logout", logout_path, method: :delete %></li>
                                                   
                                        
                                                
                                            </ul> 
                                        </li>
                                   
                                    <% end %> 
                                    
                                     
                                 
                                    
                                </ul>

                            </div>

app/views/shared/header/_top-header.html.erb
<div class="top-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="top-header-content d-flex align-items-center justify-content-between">
                    <!-- Search Form -->
                    <div class="search-form">
                        
                        <%= form_for :search,method: "get", url: search_path, html: {class: "form-inline", id: "login_form"} do |f| %>
                        <div class="form-group mx-sm-3 mb-2"> 
                             <i class="fa fa-search"> <%= f.text_field :search_text, class: "form-control text-input-login",placeholder:"Search and hint enter..." %></i>
                        </div> 
                       <%= f.submit "Search", class:"btn btn-info mb-2  " %>
                       
                        <% end %>     
                    </div>

                        <!-- Social Button -->
                        <div class="top-social-info">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>