config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  get 'favourites/index'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'
  get 'users/create'
  get '/about',to: 'home#about'
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :books
  get '/login',to: "sessions#index"
  post '/login',to: "sessions#create"
  delete '/logout',to: "sessions#destroy"
  post '/accept',to: "books#change_status"
  get '/books/get_type', to: "books#get_type"
  get '/search_admin', to: "books#search_admin"
  get '/register',to: "users#new"
  get '/search', to: "books#search_user"

  get '/add_favourite', to: "favourites#change_favourite"
  resources :users
  resources :favourites
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :favorite_books,dependent: :destroy
  has_many :reviews ,dependent: :destroy
  has_one_attached :image_url
  
  scope :by_created_at_asc, -> { order(created_at: :asc) }
  scope :by_created_at_desc, -> { order(created_at: :desc) }
  # validates :book_name, :description,:author,:publish_date, presence :true
    def display_image
      image_url.variant resize_to_limit: [360, 400]
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :is_login? ,only: [:create,:destroy,:index,:new, :show,:edit,:update,:change_status,:search_admin,:change_favourite]

    
    def index
        if is_admin?
            @books = Book.all.by_created_at_asc.paginate(page: params[:page], per_page: 15)
        else
            @books = current_user.books.paginate(page: params[:page], per_page: 15)
        end   
       
        # where(status: 1)
        # byebug
    end
    def get_type
       a = params[:type]
       byebug
       respond_to do |format|
           format.js { a  }
       end
        # where(status: 1)
        # byebug
    end
    def new
        @book = Book.new
        @name_button = "Create Book"
    end

    def search_admin
        begin
            a = params[:search][:search_text]
            book_list = Book.where("book_name LIKE '%#{a}%' ") 
            category_list = Category.where("category_name LIKE '%#{a}%'")
            book_cate = [];
            if category_list.any?
                category_list.each do |item|
                    item.books.each do |book|
                        book_cate.push book
                    end
                end
            end
            list_return = book_list + book_cate.uniq
            @books =  list_return.uniq
            # byebug
            unless is_admin?
                @books = @books.select {|item| item.user_id == current_user.id}
            end
            unless @books.any?
                flash[:danger] = "No Recored By Text"
                redirect_to :index
            end
            flash[:success] = "Search Success Have #{@books.size} Record!"
            @books =  @books.paginate(:page => params[:page], :per_page => 15)
            
          rescue
            flash[:danger] = "Failed No Record"
            redirect_to books_path
          end
       
    end
    def search_user
        a = params[:search][:search_text]
        book_list = Book.where("book_name LIKE '%#{a}%' ")
        category_list = Category.where("category_name LIKE '%#{a}%'")
        book_cate = [];
        list_return = []
        if category_list.any?
            category_list.each do |item|
                item.books.each do |book|
                    book_cate.push book
                end
            end
        end
        list_return = book_list + book_cate.uniq
        @books =  list_return.uniq
        unless @books.any?
            flash[:danger] = "No Recored By Text"
        else
            flash[:success] = "Search Success Have #{@books.size} Record!"
            @books =  @books.paginate(:page => params[:page], :per_page => 10)
        end
    end
    
    
    
    def show
        @book = Book.find_by id: params[:id]
    end
    def create
        @book= current_user.books.build book_params      
        @book.image_url.attach book_params[:image_url] 
        @book.status = 0
        if is_admin?
            @book.status = 1
            #byebug
        end
      
       if @book.save
            if current_user.role == 0
                list_admin = User.where(role: 1)
                list_admin.each do |item|
                    BookMailer.user_to_admin_email(item, "Pending Book",@book).deliver
                end
               # byebug
            end
            flash[:success] = "Create Book Success !"
                #byebug
            redirect_to books_path
       else
            #byebug
            flash.now[:danger] = "Create Book Failed !"
            render :new
       end
       
    end
    
    def destroy
        @book = Book.find_by id: params[:id]
        if @book.destroy  
            flash[:success] = "Delete Success !"
        else
            flash[:danger] = "Delete Failed !"
        end
        redirect_to books_path
    end
    
    def edit
       @book = Book.find(params[:id]) 
       @name_button = "Update Book"
    end

    def update
        @book =Book.find(params[:id])
        if @book.update(book_params)
            flash[:success] = "Update Success !"
            redirect_to books_path
        end
    end

    def change_status
        begin
            if is_admin?
                @book = Book.find_by id: params[:id]
                unless @book.status == params[:status]
                    @book.update status: params[:status]
                    temp = Book.find_by id: params[:id]
                    if temp.status == 1
                    BookMailer.admin_to_user_email(@book.user, "Thankyou!").deliver_now
                    flash[:success] = "Change Success !"
                    # byebug
                    end
                end
            end
            redirect_to books_path
            
        rescue => exception
            redirect_to root_path
        end
       
    end
   
    
    
    private 
    def book_params 
        params.require(:book).permit :book_name, :description,:publish_date,:category_id,:author,:image_url
    end
    
    def is_login?
        return if current_user
        flash[:danger] = "You need Login !"
        redirect_to login_path
    end
    
    
end

app/helpers/books_helper.rb
module BooksHelper
    def get_categories
        @categories = Category.all.order("created_at DESC")
    end

    def get_books_with_rating
        @book_rating = Book.all.order("rating DESC").limit(10)
    end
    
    def get_book_with_favourites 
        
    end
    
    
end

app/views/books/_form_add_book.html.erb
<div class="container single-post-details-area form-add-book">
    <h3 style="text-align: center;">Create Book</h3>

    <%= form_for @book do |f| %> 
      <div class="form-group">
        <%= f.label :book_name %> 
        <%= f.text_field :book_name, class: "form-control",placeholder: "Enter Book Name",required: 'true' %> 
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <%= f.label :author  %> 
      <%= f.text_field :author, class:"form-control",id:"exampleInputPassword1",placeholder:"Enter Author Name",required: 'true'%> 
    </div>
    <div class="form-group">
      <%= f.label :Categories %> 
      <%= f.select :category_id, Category.pluck(:category_name, :id),{},{required: 'true', autofocus: 'true', class: 'form-control'} %>
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Publish Date</label>
    <%= f.date_field :publish_date, as: :datetime_picker, class: "form-control",id:"datepicker",required: 'true'%> 
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Description</label>
     <%= f.cktext_area :description, rows: 10 , class: "form-control ckeditor", id: "editor", required: 'true'%>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Cover Image </label>
    <%= f.file_field :image_url, accept: "image/jpeg,image/gif,image/png" , required: 'true'%>
  </div>
  
   <%= f.submit @name_button, class:"btn btn-success form-control"%>
    <% end  %> 

</div>

app/views/books/_post-content-area.html.erb
 <div class="single-post-details-area">
                            <div class="post-thumbnail mb-30">
                                <img src="img/blog-img/1.jpg" alt="">
                            </div>
                            <div class="post-content">
                                <p class="post-date"><%= time_ago_in_words @book.created_at %> ago.</p>
                                <h4 class="post-title"><%= @book.book_name  %> </h4>
                                <div class="post-meta">
                                    <a href="#"><span>Author </span> <%= @book.author %> </a>

                                    <a href="#"><i class="fa fa-eye"></i> 192</a>
                                    <a href="#"><i class="fa fa-comments"></i> 08</a>
                                </div>
                                <div class="post-meta">
                                    <a href="#"><span>recommended by</span> <%= @book.user.user_name %> </a>
                                </div>
                               <p><%= @book.description.html_safe unless @book.description.nil? %></p>

                               <%= image_tag @book.display_image if @book.image_url.attached? %>
                               <% if is_admin? || current_user.id == @book.user.id  %> 

                               <%= image_tag @book.image_url.variant(resize_to_limit: [100, 100]) if @book.image_url.attached? %>
                               <div class="row" style="margin-top: 3%;margin-left: 1%;">
                                    
                                     <%= link_to "Come Back", books_path ,class:"btn btn-success" %>
                                    
                                     <%= link_to "Edit Book", edit_book_path(@book),class:"btn btn-info btn-edit-book" %>
                               </div>
                                <% end %> 
                              
                                
                            </div>
                        </div>

app/views/books/index.html.erb
<% provide :title, "Manage Books" %> 
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render "shared/header-area"  %> 
<div class="breadcrumb-area" style= "padding-bottom: 0;"> 
    <div class="container">
        <div class="row">
                <div class="col-12">
                    <%= image_tag  "breadcrumb-line.png",style:"height: auto;max-width: 100%;" %>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Blog List</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Blog Single</li>
                        </ol>
                    </nav>
                </div>
            </div>

    </div>
     <h2 style="text-align: center;margin-top: 3%;margin-bottom: 2%;">All Books </h2>
     <p> 
       <% flash.each do |type, msg| %>
            <% if type == "success" %>
                <div class="alert alert-success container" style="text-align: center;"  role="alert">
                    <%= msg %> 
                </div>
            <% else %> 
                <div class="alert alert-danger container" style="text-align: center;" role="alert">
                    <%= msg %> 
                </div>
            <% end %>  
            
        <% end %>  
     </p>
    <div class="container" style="margin-top: 7%;">
         <div class="row">
                <div class="col-sm-6">
                    <%= link_to  "Add New Book", new_book_path,class:"btn btn-primary" %>
                </div>
                <div class="col-sm-6">   

    <%= form_for :search,method: "get", url: search_admin_path, html: {class: "form-inline", id: "login_form"} do |f| %>
         <div class="form-group mx-sm-3 mb-2"> 
            <%= f.text_field :search_text, class: "form-control text-input-login",placeholder:"Type Here",required:'true' %>
       </div> 
         <%= f.submit "Search", class:"btn btn-primary mb-2" %>
    <% end %>
                </div>
            </div>
    </div>

<div class="col-12">
   
  <section class="blog-content-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Blog Posts Area -->
                <div class="col-12">
                    <div class="blog-posts-area">

                        <!-- Post Details Area -->


<% if @books.any? %> 
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label for="exampleFormControlSelect1">Example select</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option>Success</option>
                <option>Pending</option>
            </select>
        </div>
    </div>
    <div class="col-sm-6">
        <%= will_paginate @books, params: { controller: :books, action: :index } ,class: "page-item",id: "paginate-admin"%>
    </div>
</div>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Book Name</th>
      <th scope="col">Author</th>
      <th scope="col">Category</th>
      <th scope="col">Rating</th>
      <th scope="col">User</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% i = 0 %> 
  <% @books.each do |item|  %> 
    <tr>
    <% i+= 1 %> 
      <th scope="row"><%= i%> </th>
      <td><%= item.book_name  %> </td>
      <td><%= item.author  %></td>
      <td><%= item.category.category_name  %></td>
      <td><%= item.rating  %></td>
      <td><%= item.user.user_name  %></td>
      <td>
            <% if item.status == 0 %> 
                <div class="alert alert-danger" role="alert" style= "text-align: center;">
                    Pending
                </div>
            <% else  %>
                <div class="alert alert-success" role="alert" style= "text-align: center;">
                    Success
                </div> 
            <% end  %> 
      </td>
      <td>
            <%= link_to  "View", book_path(item) ,class: "btn btn-outline-info",id:"btn-form-admin" %> 
           <% name = "Cancel" %> 
            <% if item.status == 0  %>
                <% name = "Accept" %> 
            <% end %> 
            <% if is_admin? %>
                <%= link_to  name, accept_path(id: item.id, status: (1-item.status)),class: "btn btn-outline-primary",id:"btn-form-admin", method: :post %> 
            <% end %>  
            
            <%= link_to  "Delete", book_path(item),class: "btn btn-danger",id:"btn-form-admin", method: :delete, data: {confirm: "You Sure "}%>                 
      </td>
   
    </tr>
     <% end  %> 
     
  </tbody>
  </div>
</table>
<% else %>
     <div class="alert alert-danger" role="alert">
             No Record Loader
    </div>
<% end %> 
<%= will_paginate @books, params: { controller: :books, action: :index } ,class: "page-item text-center",id: "paginate-admin"%>
                    </div>
                </div>

                <!-- Blog Sidebar Area -->
                
            </div>
        </div>
    </section>

</div>
<%= render "shared/instagram"  %> 

<%= render "shared/footer-area"  %>

<%= render "shared/footer-script"  %>


 

app/views/books/search_admin.html.erb
<% provide :title, "Manage Books" %> 
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render "shared/header-area"  %> 
<div class="breadcrumb-area" style= "padding-bottom: 0;"> 
    <div class="container">
        <div class="row">
                <div class="col-12">
                    <%= image_tag  "breadcrumb-line.png",style:"height: auto;max-width: 100%;" %>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Blog List</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Blog Single</li>
                        </ol>
                    </nav>
                </div>
            </div>

    </div>
     <h2 style="text-align: center;margin-top: 3%;margin-bottom: 2%;">All Books </h2>
     <p> 
       <% flash.each do |type, msg| %>
            <% if type == "success" %>
                <div class="alert alert-success container" style="text-align: center;"  role="alert">
                    <%= msg %> 
                </div>
            <% else %> 
                <div class="alert alert-danger container" style="text-align: center;" role="alert">
                    <%= msg %> 
                </div>
            <% end %>  
            
        <% end %>  
     </p>
    <div class="container" style="margin-top: 7%;">
         <div class="row">
                <div class="col-sm-6">
                    <%= link_to  "Add New Book", new_book_path,class:"btn btn-primary" %>
                </div>
                <div class="col-sm-6">
   

    <%= form_for :search,method: "get", url: search_admin_path, html: {class: "form-inline", id: "login_form"} do |f| %>
         <div class="form-group mx-sm-3 mb-2"> 
            <%= f.text_field :search_text, class: "form-control text-input-login",placeholder:"Type Here",required:'true' %>
       </div> 
         <%= f.submit "Search", class:"btn btn-primary mb-2" %>
    <% end %>
                </div>
            </div>
    </div>

<div class="col-12">
   
  <section class="blog-content-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Blog Posts Area -->
                <div class="col-12">
                    <div class="blog-posts-area">

                        <!-- Post Details Area -->


<% if @books.any? %> 
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label for="exampleFormControlSelect1">Example select</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option>Success</option>
                <option>Pending</option>
            </select>
        </div>
    </div>
    <div class="col-sm-6">
        <%= will_paginate @books, params: { controller: :books, action: :search_admin } ,class: "page-item",id: "paginate-admin"%>
    </div>
</div>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Book Name</th>
      <th scope="col">Author</th>
      <th scope="col">Category</th>
      <th scope="col">Rating</th>
      <th scope="col">User</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% i = 0 %>  
  <% @books.each do |item|  %> 
    <% if item.present? %> 
    <tr>
    <% i+= 1 %> 
      <th scope="row"><%= i%> </th>
      <td><%= item.book_name  %> </td>
      <td><%= item.author  %></td>
      <td><%= item.category.category_name  %></td>
      <td><%= item.rating  %></td>
      <td><%= item.user.user_name  %></td>
      <td>
            <% if item.status == 0 %> 
                <div class="alert alert-danger" role="alert" style= "text-align: center;">
                    Pending
                </div>
            <% else  %>
                <div class="alert alert-success" role="alert" style= "text-align: center;">
                    Success
                </div> 
            <% end  %> 
      </td>
      <td>
            <%= link_to  "View", book_path(item) ,class: "btn btn-outline-info",id:"btn-form-admin" %> 
           <% name = "Cancel" %> 
            <% if item.status == 0  %>
                <% name = "Accept" %> 
            <% end %> 
            <% if is_admin? %>
                <%= link_to  name, accept_path(id: item.id, status: (1-item.status)),class: "btn btn-outline-primary",id:"btn-form-admin", method: :post %> 
            <% end %>  
            
            <%= link_to  "Delete", book_path(item),class: "btn btn-danger",id:"btn-form-admin", method: :delete, data: {confirm: "You Sure "}%>                 
      </td>
   
    </tr>
    <% end %> 
     <% end  %> 
     
  </tbody>
  </div>
</table>
<% else %>
     <div class="alert alert-danger" role="alert">
             No Record Loader
    </div>
<% end %> 
<%= will_paginate @books, params: { controller: :books, action: :search_admin } ,class: "page-item text-center",id: "paginate-admin"%>
                    </div>
                </div>

                <!-- Blog Sidebar Area -->
                
            </div>
        </div>
    </section>

</div>
<%= render "shared/instagram"  %> 

<%= render "shared/footer-area"  %>

<%= render "shared/footer-script"  %>


 

app/views/books/search_user.html.erb
<% provide :title ,"Search Page" %> 
<div class="preloader d-flex align-items-center justify-content-center">
    <div class="circle-preloader">
        <%= image_tag "logo.png" %>
        <div class="foode-preloader">
            <span></span>
        </div>
    </div>
</div>

<!-- ##### Header Area Start ##### -->
<%= render "shared/header-area"  %> 
<!-- ##### Header Area End ##### -->
 <p> 
       <% flash.each do |type, msg| %>
            <% if type == "success" %>
                <div class="alert alert-success container" style="text-align: center;"  role="alert">
                    <%= msg %> 
                </div>
            <% else %> 
                <div class="alert alert-danger container" style="text-align: center;" role="alert">
                    <%= msg %> 
                </div>
            <% end %>  
            
        <% end %>  
     </p>


<section class="blog-content-area section-padding-100">
    <div class="container">


        <div class="row justify-content-center">
            <!-- Blog Posts Area -->
            <div class="col-12 col-lg-8">
                
                 
                <div class="blog-posts-area">

                    <!-- Single Blog Post -->
                    <% if @books.any? %>
                <div>
                    <%= will_paginate @books, params: { controller: :books, action: :search_user } ,class: "page-item",id: "paginate-user"%>
                </div>
                    <%  @books.each do |book| %>
                    <div class="single-blog-post d-flex flex-wrap mt-50">
                        <!-- Thumbnail -->
                        <div class="post-thumbnail mb-50">
                            <a href="#">
                                <div class="limit-image">
                                <% if book.image_url.attached? %> 
                                <%= image_tag book.display_image  %>
                                <% else %> 
                                    <%= image_tag "1.jpg"  %>
                                <% end %> 
                                </div>
                            </a>
                        </div>
                        <!-- Content -->
                        <div class="post-content mb-50">
                            <p class="post-date"><%= book.publish_date %></p>
                            <a href="#" class="post-title">
                                <h4><%= book.book_name %></h4>
                            </a>
                            <div class="post-meta">
                                <a href="#"><span>by</span> <%= book.author %></a>
                                <a href="#"><i class="fa fa-eye"></i> 192</a>
                                <a href="#"><i class="fa fa-comments"></i> 08</a>
                            </div>
                            <p class="post-excerpt"><%= book.description.html_safe unless book.description.nil? %></p>
                            <%= link_to  "Continue Reading", book_path(book) ,class:"read-more-btn"%>
                           
                              <% if current_user.favorite_books.where(book_id: book.id).present? %> 
                               
                                 <i class="fa fa-thumbs-up" aria-hidden="true"> 
                                    <%= link_to  "Have Liked", favourite_path(id: book.id), class: "btn btn-primary",method: :delete%>
                                </i>
                                <% else %>
                                       <i class="fa fa-thumbs-up" aria-hidden="true"> 
                                    <%= link_to  "Like", add_favourite_path(id: book.id), class: "btn btn-success"%>
                                </i>
                                <% end %> 
                        </div>
                        <!-- Post Curve Line -->
                        <%= image_tag  "post-curve-line.png", class:"post-curve-line"%>

                    </div>
                    <% end %>

                    <% end %>
                </div>
            </div>


            <%= render "shared/blog-content/blog-sidebar-area" %>
        </div>
    </div>
</section>

<!-- ##### Instagram Area Start ##### -->
<%= render "shared/instagram"  %> 
<!-- ##### Instagram Area End ##### -->

<!-- ##### Footer Area Start ##### -->
<%= render "shared/footer-area"  %> 

<%= render "shared/footer-script" %>